### ISSUE TITLE
Flacky test RoundRobinStrategyTest.testSkipConnections

### ISSUE THREAD

**Issue by isopov** [tarantool/cartridge-java#22] opened 2020-10-18 11:35 UTC
Sometimes this test fails with 
```
java.util.concurrent.CompletionException: org.opentest4j.AssertionFailedError: Unexpected exception thrown: io.tarantool.driver.exceptions.NoAvailableConnectionsException: No available connections

	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:325)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1809)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:1676)
Caused by: org.opentest4j.AssertionFailedError: Unexpected exception thrown: io.tarantool.driver.exceptions.NoAvailableConnectionsException: No available connections
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3005)
	at io.tarantool.driver.core.RoundRobinStrategyTest.lambda$testSkipConnections$9(RoundRobinStrategyTest.java:119)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
	... 3 more
Caused by: io.tarantool.driver.exceptions.NoAvailableConnectionsException: No available connections
	at io.tarantool.driver.core.TarantoolConnectionSelectionStrategies$RoundRobinStrategy.next(TarantoolConnectionSelectionStrategies.java:57)
	at io.tarantool.driver.core.RoundRobinStrategyTest.lambda$testSkipConnections$8(RoundRobinStrategyTest.java:119)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 7 more
```
and sometimes it does pass.

`@RepeatedTest(value = 100)` does not help in reproducing - it seems that only first repetition can fail and all the others will always pass.

**Comment by akudiyar** [comment] 2020-10-18 19:27
What is your environment? Never seen this problem on my Mac + Oracle JDK 1.8, and it hasn't been reported by @savolgin on a Linux VM.

**Comment by isopov** [comment] 2020-10-19 06:52
```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
```
(default java11 on ubuntu 18.04)

**Comment by akudiyar** [comment] 2020-10-21 18:16
Talked to Sergey, he reported that the bug is reproducible. Assigned to myself.

**Comment by isopov** [comment] 2020-11-10 07:22
AFAIU you have reduced flakiness probability, but did not eliminate it.
Increasing parameters leads to this test failing all the time on my machine:
```
    @Test
    public void testSkipConnections() {
        List<TarantoolConnection> connections = IntStream.range(1, 11)
                .mapToObj(i -> new CustomConnection(String.format("127.0.0.%d", i), 3000 + i))
                .peek(c -> {
                    if (c.getPort() < 3006) {
                        c.setConnected(false);
                    }
                })
                .collect(Collectors.toList());

        TarantoolClientConfig config = new TarantoolClientConfig();
        ConnectionSelectionStrategy strategy = RoundRobinStrategyFactory.INSTANCE.create(config, connections);

        ExecutorService executor = Executors.newFixedThreadPool(10);
        List<CompletableFuture<?>> futures = new ArrayList<>(10);
        for (int i = 0; i < 1000; i++) {
            futures.add(CompletableFuture.runAsync(() -> {
                for (int j = 0; j < 1000; j++) {
                    assertDoesNotThrow(() -> ((CustomConnection) strategy.next()).count());
                }
            }, executor));
        }
        futures.forEach(CompletableFuture::join);

        for (TarantoolConnection c : connections) {
            if (((CustomConnection) c).getPort() < 3006) {
                assertEquals(0, ((CustomConnection) c).getCount(), "Closed connection must have been used 0 times");
            } else {
                assertEquals(200000, ((CustomConnection) c).getCount(), "Active connection must have been used 20 times");
            }
        }
    }
```
Increasing maxAttempts in RoundRobinStrategy - `this.maxAttempts = connections.size() * 10;` leads to this test passing with increased counters, but still this should only decrease probability of fail. And the more attempts - the more this algorithm seems like a busy loop.

**Comment by akudiyar** [comment] 2020-11-10 10:14
You're right, I tried to decrease the probability of failure since this test shouldn't check cases when the strategy runs out of attempts.

I think the root cause is the random order of futures finishing, which in some cases lead to the following situation: one thread skips a number of closed connections, handles the control, at this time other threads take connections and modify the state of the cycling iterator, and when the first thread wakes up, its attempts counter is not modified, by the iterator state is modified so that it skips more connections and comes to the dead end.

I will think about the shared usage of the iterator in this case, maybe the attempts counter need to be volatile.

**Comment by isopov** [comment] 2020-11-10 10:21
> maybe the attempts counter need to be volatile.

it is local variable - it can not be volatile. Assume you have two connections and two threads requesting them.
- Thead1 requests connection and receives Con1 which is open
- Thread2 requests connection and probes Con2 which is closed - attempts are now 1
- Thread1 requests one more connection and receives Con1 again
- Thread2 continues its first attempt and probes Con2 again and fails again - attempts are now 2
- Thread1 requests one more connection and receives Con1 again
- Thread2 continues its first attempt and probes Con2 again and fails again - attempts are now 3
... so on

If you are unlucky enough any number of attempts will be not enough.

**Comment by akudiyar** [comment] 2020-11-10 10:27
> it is local variable - it can not be volatile

Of course, now it cannot, but if we have shared iterator state, the number of attempts or position or any other stop-marker should be also volatile.
btw, in the driver there is a built-in connection failure listener which closes and reopens all connections if any of them closes. It is rather hard but removes the "lack of connections" problem and allows adapting to the cluster memebership changes.

**Closed** 2021-03-04 20:20 UTC
Labels: 2sp, bug, p2
